# -*- mode: ruby -*-
# vim: set ft=ruby :

home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :otuslinux => {
        :box_name => "centos/8",
        :box_version => "1905.1",
        :ip_addr => '192.168.11.102',
	:disks => {
		:sata1 => {
			:dfile => home + '/VirtualBox VMs/sata1.vdi',
			:size => 250, # Megabytes
			:port => 1
		},
		:sata2 => {
            :dfile => home + '/VirtualBox VMs/sata2.vdi',
            :size => 250, # Megabytes
			:port => 2
		},
        :sata3 => {
            :dfile => home + '/VirtualBox VMs/sata3.vdi',
            :size => 250, # Megabytes
            :port => 3
        },
        :sata4 => {
            :dfile => home + '/VirtualBox VMs/sata4.vdi',
            :size => 250, # Megabytes
            :port => 4
        },
        :sata5 => {
            :dfile => home + '/VirtualBox VMs/sata5.vdi',
            :size => 250, # Megabytes
            :port => 5
        }
	}
  },
}

Vagrant.configure("2") do |config|
    if Vagrant.has_plugin?("vagrant-timezone") # vagrant plugin install vagrant-timezone
        config.timezone.value = "Asia/Almaty"
      end
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.network "private_network", ip: boxconfig[:ip_addr]
        box.vm.hostname = "vm-hw04-zfs"
        box.vm.provider :virtualbox do |vb|
                vb.name = "hw04.otus-zfs"
                vb.memory = "1024"
                vb.cpus = "2"
                needsController = false
		boxconfig[:disks].each do |dname, dconf|
			    unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                            needsController =  true
                        end
		end
                if needsController == true
                    vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                    boxconfig[:disks].each do |dname, dconf|
                        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                    end
                end
         end
 	box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                #CentOS 8 
                dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
                yum install -y mdadm smartmontools gdisk wget tree mc iotop sysstat htop ncdu
                #yum update -y
                #reboot
        SHELL
    box.vm.provision "shell", path: "script.sh"    
      end
  end
end

