# -*- mode: ruby -*-
# vim: set ft=ruby :

home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.102',
	:disks => {
		:sata1 => {
			:dfile => home + '/VirtualBox VMs/sata1.vdi',
			:size => 250, # Megabytes
			:port => 1
		},
		:sata2 => {
            :dfile => home + '/VirtualBox VMs/sata2.vdi',
            :size => 250, # Megabytes
			:port => 2
		},
        :sata3 => {
            :dfile => home + '/VirtualBox VMs/sata3.vdi',
            :size => 250, # Megabytes
            :port => 3
        },
        :sata4 => {
            :dfile => home + '/VirtualBox VMs/sata4.vdi',
            :size => 250, # Megabytes
            :port => 4
        }
	}
  },
}

Vagrant.configure("2") do |config|
    if Vagrant.has_plugin?("vagrant-timezone") # vagrant plugin install vagrant-timezone
        config.timezone.value = "Asia/Almaty"
      end
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.network "private_network", ip: boxconfig[:ip_addr]
        box.vm.hostname = "vm-hw02"
        box.vm.provider :virtualbox do |vb|
                vb.name = "hw02.otus"
                vb.memory = "1024"
                vb.cpus = "1"
                needsController = false
		boxconfig[:disks].each do |dname, dconf|
			    unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                            needsController =  true
                        end
		end
                if needsController == true
                    vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                    boxconfig[:disks].each do |dname, dconf|
                        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                    end
                end
         end
 	box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                yum install -y mdadm smartmontools hdparm gdisk wget #iotop htop ncdu mc
                yum update

                mkdir /mnt/raid5
                mdadm --create --verbose /dev/md0 --level=5  --raid-devices=4 /dev/sd{b,c,d,e}
                
                mkdir /etc/mdadm
                echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
                mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
                
                mkfs.ext4 /dev/md0
                
                echo "/dev/md0 /mnt/raid5 ext4 defaults 0 0" >> /etc/fstab     

        reboot
  	  SHELL
      end
  end
end

